on:
  push:
    branches:
      - master





jobs:
  build:
    runs on: ubuntu-lates

    steps:
      - name: 'Testing Github action'
        run: pwd

      - name: 'Testing Printing'
        run: echo madyan
